version: '3.8'

services:
  app:
    image: ${account_id}.dkr.ecr.${region}.amazonaws.com/parking-backend:latest
    restart: always
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/server.js"]
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgis/postgis:15-3.3-alpine
    restart: always
    environment:
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: SuperSecurePass2026!
      POSTGRES_DB: parking_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parking_user -d SuperSecurePass2026!"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    # Usamos un healthcheck básico que funciona en la versión alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_prod:
  redis_data_prod: